# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Runner' do
use_frameworks!
 flutter_application_path = '/Users/qiuming/Desktop/EZFlutter'
  eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)
  
end
